version: '3'
services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: foxtrafficker/coc-toolbox:backend-latest
    ports:
      - "8000:8000"
    networks:
      - myapp-network


  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: foxtrafficker/coc-toolbox:frontend-latest
    deploy:
      resources:
        limits:
          memory: 512M  # 设置内存限制为 512 MB
        reservations:
          memory: 256M  # 设置内存保留为 256 MB
    ports:
      - "3000:3000"
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge
