version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"  # 将主机的8080端口映射到容器的8080端口
    volumes:
      - ./backend:/app  # 挂载主机的 ./backend 目录到容器的 /app 目录
    networks:
      - myapp-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"  # 将主机的3000端口映射到容器内的3000端口（Next.js 默认端口）
    volumes:
      - ./frontend:/app  # 挂载主机的 ./frontend 目录到容器的 /app 目录
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge
